EA2/Controllers/CompetidoresController.cs
using Entidades;
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EA2.Controllers
{
    public class CompetidoresController : Controller
    {
        ServicioCompetidores servicioCompetidores;
        public CompetidoresController()
        {
            EA2Entities context = new EA2Entities();
            servicioCompetidores = new ServicioCompetidores(context);
        }
        // GET: Competidores
        public ActionResult ListaCompetidores()
        {
            List<Competidor> listaCompetidores = servicioCompetidores.ObtenerTodos();
            return View(listaCompetidores);
        }

        [HttpGet]
        public ActionResult AltaCompetidor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AltaCompetidor(Competidor competidor)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                servicioCompetidores.GuardarCompetidor(competidor);
            }
            return RedirectToAction("ListaCompetidores");
        }
    }
}

EA2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EA2.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Bienvenido()
        {
            return View();
        }
    }
}

EA2/Controllers/PremiosController.cs
using Entidades;
using Servicios;
using System.Collections.Generic;
using System.Web.Mvc;

namespace EA2.Controllers
{
    public class PremiosController : Controller
    {
        ServicioPremios servicioPremios;
        ServicioCompetidores servicioCompetidores;
        public PremiosController()
        {
            EA2Entities context = new EA2Entities();
            servicioPremios = new ServicioPremios(context);
            servicioCompetidores = new ServicioCompetidores(context);
        }
        // GET: Premios
        public ActionResult ListaPremios()
        {
            List<Competidor> listaCompetidores = servicioCompetidores.ObtenerCompetidoresConPremios();
            return View(listaCompetidores);
        }

        [HttpGet]
        public ActionResult AltaPremios()
        {
            var listaCompetidores = servicioCompetidores.ObtenerTodos();
            ViewBag.Competidores = new SelectList(listaCompetidores, "Id", "Nombre");
            return View();
        }

        [HttpPost]
        public ActionResult AltaPremios(Premios premio)
        {
            if (!ModelState.IsValid)
            {
                var listaCompetidores = servicioCompetidores.ObtenerTodos();
                ViewBag.Competidores = new SelectList(listaCompetidores, "Id", "Nombre");
                return View();
            }
            servicioPremios.GuardarPremio(premio);

            return RedirectToAction("ListaPremios");
        }
    }
}

EA2/Views/Competidores/AltaCompetidor.cshtml
@model Entidades.Competidor
@{
    ViewBag.Title = "AltaCompetidor";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
<h2 class="text-white text-center">Alta nuevo Competidor</h2>
<div class="container col-md-6 card">
    @using ((Html.BeginForm("AltaCompetidor", "Competidores", FormMethod.Post)))
    {
        <div class="form-group">
            <label>Nombre:</label>
            @Html.EditorFor(competidor => competidor.Nombre, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese nombre" } })
            @Html.ValidationMessageFor(m => m.Nombre, "", new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    }

</div>

EA2/Views/Competidores/ListaCompetidores.cshtml
@model List<Entidades.Competidor>
@{
    ViewBag.Title = "ListaCompetidores";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
<div class="container col-md-8">
    <h2 class="text-white text-center">Listado de Competidores</h2>
    @Html.ActionLink("Crear nuevo Competidor", "AltaCompetidor", "Competidores", new { @class = "btn btn-primary" })
    @if (Model.Count == 0)
    {
        <div class="alert alert-info" role="alert">
            No se encontraron Competidores registrados
        </div>
    }
    else
    {
        <div class="card">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Nombre</th>

                    </tr>
                </thead>
                <tbody>

                    @foreach (Entidades.Competidor competidor in Model)
                    {
                        <tr>
                            <th scope="row">@competidor.Id</th>
                            <td>@competidor.Nombre</td>

                        </tr>

                    }

                </tbody>

            </table>
        </div>
    }
</div>

EA2/Views/Home/Bienvenido.cshtml
@{
    ViewBag.Title = "Bienvenido";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

    <div class="container">
        <h1 class="margin text-center text-white">Bienvenido a la evaluación de aprendizaje Nro 2 </h1>
        <h4> @Html.ActionLink("- Ir a Gestión de Competidores", "ListaCompetidores", "Competidores","", new{@class = "text-dark" })</h4>

        <h4>@Html.ActionLink("- Ir a Gestión de Premios", "ListaPremios", "Premios","", new { @class = "text-dark" })</h4>
    </div>

EA2/Views/Premios/AltaPremios.cshtml
@model Entidades.Premios
@{
    ViewBag.Title = "AltaPremios";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 class="text-white text-center">Alta nuevo Premio</h2>
<div class="container col-md-6 card">
    @using ((Html.BeginForm("AltaPremios", "Premios", FormMethod.Post)))
    {
        <div class="form-group">
            <div>
                @Html.LabelFor(p => p.Competidor.Nombre, "Competidor")
                @Html.DropDownList("IdCompetidor", ViewBag.Competidores as SelectList, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.IdCompetidor, "", new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(p => p.Año)
                @Html.EditorFor(premio => premio.Año, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese año" } })
                @Html.ValidationMessageFor(m => m.Año, "", new { @class = "text-danger" })
            </div>
            <div>

                @Html.LabelFor(p => p.CantidadPremios, new { @class = "label" })
                @Html.EditorFor(premio => premio.CantidadPremios, new { htmlAttributes = new { @class = "form-control", @placeholder = "Ingrese cantidad de premios" } })
                @Html.ValidationMessageFor(m => m.CantidadPremios, "", new { @class = "text-danger" })
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    }

</div>

EA2/Views/Premios/ListaPremios.cshtml
@model List<Entidades.Competidor>
@{
    ViewBag.Title = "ListaPremios";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<div class="container col-md-8">
    <h2 class="text-white text-center">Listado de Premios</h2>
    @Html.ActionLink("Crear nuevo Premio", "AltaPremios", "Premios", new { @class = "btn btn-primary" })
    @if (Model.Count == 0)
    {
        <div class="alert alert-info" role="alert">
            No se encontraron Premios registrados
        </div>
    }
    else
    {

        <div class="card">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Año</th>
                        <th scope="col">Cantidad Premios</th>
                        <th scope="col">Competidor</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Entidades.Competidor competidor in Model)
                    {
                        <tr>

                            <td>
                                @foreach (Entidades.Premios premio in competidor.Premios)
                                {

                                    <p> @premio.Año </p>

                                }
                            </td>
                            <td>
                                @foreach (Entidades.Premios premio in competidor.Premios)
                                {
                                    <p> @premio.CantidadPremios </p>
                                }
                            </td>
                            <td>@competidor.Nombre</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    }
</div>

EA2/Views/Shared/_LayoutPrincipal.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <link href="~/Content/Css/estilos.css" rel="stylesheet" />
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">EA2</a>
            <ul class="navbar-nav">
                <li class="nav-item active">
                    @Html.ActionLink("Inicio", "Bienvenido", "Home")
                </li>
            </ul>
        </nav>

        @RenderBody()
    </div>

    <div class="footer">
        <div class="container text-center">
            <span class="text-muted">Alumna: Aguayo Guillén, Diana | DNI: 94.989.758</span>
        </div>
    </div>
</body>
</html>